### ISSUE TITLE
can this run on Cobalt Strike 4.5?

### ISSUE THREAD

**Issue by m0s30** [REDMED-X/InjectKit#1]
Can this bof run on Cobalt Strike 4.5？

i have a error
![image](https://github.com/REDMED-X/InjectKit/assets/54650671/06c65648-1bcc-4a3c-a1d8-060a428cb1f3)

**Comment by REDMED-X** [comment]
The kit is only tested and used from version 4.7 and above (it is currently at version 4.9.x).  From your output, I'm not sure what the issue could be.
